### ISSUE TITLE
Cannot build on Android Device

### ISSUE THREAD

**Issue by vickygaugau** [honvidan/flutter_images_picker#1]
Hi, i am using this lib and iOS is worked
But when i build on android device or simulator, this is an issues.
Can you help me.?
Thanks

![Screen Shot 2023-07-12 at 10 56 02](https://github.com/honvidan/flutter_images_picker/assets/4328044/ffa7f0d4-9eeb-44a0-91b5-d92f32ac22a4)

**Comment by beginner-byte** [comment]
同样的问题

**Comment by honvidan** [comment]
@vickygaugau Please change version to 0.1.2, This issue is solved.
@beginner-byte 下载0.1.2，问题已经解决了。
